# docs [https://starship.rs/config/]

prompt_order = [
    "battery",
    "time",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "line_break",
    "rust",
    "nodejs",
    "env_var",
    "cmd_duration",
    "line_break",
    "character"
]

[directory]
prefix = "in ğŸ—ºï¸  "

[time]
disabled = false
format = "ğŸ•°ï¸  %I:%M%p"

[character]
symbol = "âœ"

[package]
disabled = true

[nodejs]
symbol = "ğŸ¸ node "

[rust]
symbol = "ğŸ¦€ rust "
