# docs [https://starship.rs/config/]

format = """$battery\
    $time\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $env_var\
    $cmd_duration\
    $line_break\
    $character\
"""

[[battery.display]]
threshold = 100

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "

[time]
disabled = false
time_format = "%H:%M"
format = "[$time]($time_style)"

[package]
disabled = true

[nodejs]
symbol = "ğŸ¸ node "

[rust]
symbol = "ğŸ¦€ rust "
